#! /usr/bin/env bash

java -jar utils/asc.jar -md -import build/libs/builtin.abc $1.as

js build/ts/shell.js -x -bl $1.abc -w ri

colordiff -s -W 150 -y --difftype=diffy <(js build/ts/shell.js -x -bl $1.abc) <(utils/avmshell/mac/avmshell $1.abc)
