/* -*- Mode: js; js-indent-level: 2; indent-tabs-mode: nil; tab-width: 2 -*- */
/* vim: set shiftwidth=2 tabstop=2 autoindent cindent expandtab: */
/*
 * Copyright 2013 Mozilla Foundation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

var load = function (scriptPath) {
  importScripts([scriptPath]);
}
if (typeof console === 'undefined') {
  this.console = {};
}
if (console.time) {
  console.time = console.timeEnd = function () {};
}

/* Autogenerated parser references: base=../../ */
console.time("Load Parser Dependencies");
load("../../build/ts/base.js");
load("../../build/ts/tools.js");
console.timeEnd("Load Parser Dependencies");

console.time("Load SWF Parser");
load("../../build/ts/swf.js");
console.timeEnd("Load SWF Parser");

/* Autogenerated parser references end */

var loader = new Shumway.SWF.ResourceLoader(this, true);
