var SWF;
var swf;
swf.tags;
swf.fileAttributes;
swf.swfVersion;
swf.parseTime;
swf.bytesLoaded;
swf.bytesTotal;
var options;
options.onstart;
function OptionSet() {}
var coreOptions;
coreOptions.register
function Multiname() {}
Multiname.fromSimpleName;
Multiname.isMultiname;
Multiname.needsResolution;
Multiname.isQName;
Multiname.isRuntimeName;
Multiname.isRuntime;
Multiname.getQualifiedName;
Multiname.prototype.getOriginalName;
var Class;
Class.extend;
Class.linkNatives;
Class.classInfo;
Class.classInfo.instanceInfo;
Class.classInfo.instanceInfo.name;
var flash;
flash.display;
flash.display.Loader = function () {};
flash.display.Stage;
flash.events;
flash.events.Event;
var loader;
loader.contentLoaderInfo;
loader._load;
loader._stage;
var avm2;
avm2.systemDomain;
avm2.systemDomain.getClass;
var Domain;
Domain.coerceCallable;
var loaderInfo;
loaderInfo._addEventListener;
var Counter;
var metrics;
metrics.Counter;
metrics.Timer;
var svgElement;
svgElement.createSVGMatrix;
var $;
$.a;
$.actionsData;
$.adjustment;
$.advance;
$.advanceBits;
$.align;
$.alpha;
$.alphaData;
$.alphaMultiplier;
$.alphaOffset;
$.anchorDeltaX;
$.anchorDeltaY;
$.angle;
$.ansi;
$.ascent;
$.autoSize;
$.b;
$.backgroundColor;
$.bbox;
$.bboxMorph;
$.bias;
$.bitmapId;
$.blend;
$.blendMode;
$.blue;
$.blueMultiplier;
$.blueOffset;
$.blurX;
$.blurY;
$.bmpCache;
$.bmpData;
$.bold;
$.border;
$.bottom;
$.buttonActions;
$.c;
$.cache;
$.characters;
$.clamp;
$.className;
$.clip;
$.clipDepth;
$.code1;
$.code2;
$.codes;
$.color;
$.colorMorph;
$.colorTableSize;
$.colors;
$.columns;
$.compositeSource;
$.condition;
$.controlDeltaX;
$.controlDeltaY;
$.count;
$.cxform;
$.d;
$.data;
$.deblock;
$.defaultColor;
$.deltaX;
$.deltaY;
$.depth;
$.descent;
$.distance;
$.divisor;
$.doAbc;
$.endCapStyle;
$.entries;
$.envelopeCount;
$.envelopes;
$.eob;
$.eoe;
$.eos;
$.eot;
$.events;
$.exports;
$.fillStyle;
$.fillStyle0;
$.fillStyle1;
$.fillStyles;
$.fillWinding;
$.filterCount;
$.filters;
$.finalTag;
$.flags;
$.focalPoint;
$.focalPointMorph;
$.fontClass;
$.fontHeight;
$.fontId;
$.format;
$.frameCount;
$.frameRate;
$.glyphBits;
$.glyphCount;
$.glyphIndex;
$.glyphs;
$.green;
$.greenMultiplier;
$.greenOffset;
$.hasAlpha;
$.hasBackgroundColor;
$.hasClassName;
$.hasColor;
$.hasCxform;
$.hasEnvelope;
$.hasEvents;
$.hasFill;
$.hasFillStyle0;
$.hasFillStyle1;
$.hasFilters;
$.hasFont;
$.hasFontClass;
$.hasImage;
$.hasInPoint;
$.hasLayout;
$.hasLineStyle;
$.hasLoops;
$.hasMatrix;
$.hasMaxLength;
$.hasMetadata;
$.hasMoveX;
$.hasMoveY;
$.hasName;
$.hasNewStyles;
$.hasOutPoint;
$.hasRatio;
$.hasStrokes;
$.hasText;
$.hasVisibility;
$.height;
$.higlightColor;
$.html;
$.id;
$.idleToOverDown;
$.idleToOverUp;
$.imgData;
$.inPoint;
$.incomplete;
$.indent;
$.initialText;
$.innerShadow;
$.interpolationMode;
$.isGeneral;
$.isMorph;
$.isStraight;
$.isVertical;
$.italic;
$.joinStyle;
$.kerning;
$.keyCode;
$.keyPress;
$.knockout;
$.labels;
$.language;
$.latencySeek;
$.leading;
$.left;
$.leftMargin;
$.length;
$.lineStyle;
$.lineStyles;
$.loopCount;
$.mapOffset;
$.matrix;
$.matrixMorph;
$.maxLength;
$.mimeType;
$.miterLimitFactor;
$.mouseEventFlags;
$.move;
$.moveX;
$.moveY;
$.multiline;
$.name;
$.network;
$.noClose;
$.noCrossDomainCaching;
$.noHscale;
$.noMultiple;
$.noSelect;
$.noVscale;
$.nonScalingStrokes;
$.offsetMorph;
$.offsets;
$.onConstruct;
$.onData;
$.onDragOut;
$.onDragOver;
$.onEnterFrame;
$.onInitialize;
$.onKeyDown;
$.onKeyUp;
$.onLoad;
$.onMouseDown;
$.onMouseMove;
$.onMouseUp;
$.onPress;
$.onRelease;
$.onReleaseOutside;
$.onRollOut;
$.onRollOver;
$.onTop;
$.onUnload;
$.outDownToIdle;
$.outDownToOverDown;
$.outPoint;
$.overDownToIdle;
$.overDownToOutDown;
$.overDownToOverUp;
$.overUpToIdle;
$.overUpToOverDown;
$.passes;
$.password;
$.pixelHinting;
$.place;
$.playbackRate;
$.playbackSize;
$.playbackType;
$.pos44;
$.preserveAlpha;
$.props;
$.ratio;
$.ratioMorph;
$.ratios;
$.readonly;
$.records;
$.recordsMorph;
$.red;
$.redMultiplier;
$.redOffset;
$.relativeUrls;
$.resolution;
$.right;
$.rightMargin;
$.rows;
$.samplesCount;
$.scalingStrokes;
$.scenes;
$.shiftJis;
$.smallText;
$.soundClassName;
$.soundData;
$.soundFormat;
$.soundId;
$.soundInfo;
$.soundRate;
$.soundSize;
$.soundType;
$.splitter;
$.spreadMode;
$.spriteId;
$.startCapStyle;
$.stateDown;
$.stateHitTest;
$.stateOver;
$.stateUp;
$.stop;
$.streamCompression;
$.streamRate;
$.streamSize;
$.streamType;
$.strength;
$.strokeBbox;
$.strokeBboxMorph;
$.symbolId;
$.top;
$.trackAsMenu;
$.tx;
$.ty;
$.type;
$.useDirectBlit;
$.useGpu;
$.useOutlines;
$.variableName;
$.visibility;
$.volumeLeft;
$.volumeRight;
$.wasStatic;
$.weights;
$.wide;
$.wideOffset;
$.width;
$.widthMorph;
$.wordWrap;
$.xMin;
$.xMax;
$.yMin;
$.yMax;
var $0;
$0.left;
$0.right;
$0.top;
$0.bottom;
var $2;
$2.className;
$2.name;
$2.offset;
$2.symbolId;
var $32;
$32.angle;
$32.bias;
$32.blurX;
$32.blurY;
$32.clamp;
$32.colors;
$32.columns;
$32.compositeSource;
$32.defaultColor;
$32.distance;
$32.divisor;
$32.higlightColor;
$32.innerShadow;
$32.knockout;
$32.matrix;
$32.onTop;
$32.passes;
$32.preserveAlpha;
$32.ratios;
$32.rows;
$32.strength;
$32.type;
$32.weights;
var $5;
$5.frame;
$5.name;
var $29;
$29.eob;
$29.blend;
$29.hasFilters;
$29.stateHitTest;
$29.stateDown;
$29.stateOver;
$29.stateUp;
$29.symbolId;
$29.depth;
$29.matrix;
$29.cxform;
$29.filterCount;
$29.filters;
$29.blendMode;

function readSi8($bytes, $stream) {}
function readSi16($bytes, $stream) {}
function readSi32($bytes, $stream) {}
function readUi8($bytes, $stream) {}
function readUi16($bytes, $stream) {}
function readUi32($bytes, $stream) {}
function readFixed($bytes, $stream) {}
function readFixed8($bytes, $stream) {}
function readFloat16($bytes, $stream) {}
function readFloat($bytes, $stream) {}
function readDouble($bytes, $stream) {}
function readEncodedU32($bytes, $stream) {}
function readBool($bytes, $stream) {}
function align($bytes, $stream) {}
function readSb($bytes, $stream, size) {}
function readUb($bytes, $stream, size) {}
function readFb($bytes, $stream, size) {}
function readString($bytes, $stream, length){}
function readBinary($bytes, $stream, size) {}
var $stream;
$stream.remaining;
var stream;
stream.bytes;
stream.pos
stream.end;
stream.bitBuffer;
stream.bitLength;
stream.align;
stream.ensure;
stream.remaining;
stream.substream;
stream.push;

