#!/bin/bash
SWF_FILE=$(cd $(dirname $1); pwd)/$(basename $1)
JSSHELL=js
MAINFILE=./build/ts/shell.js
SAVED_DIR=$(pwd)
SCRIPT_PATH=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

cd $SCRIPT_PATH
$JSSHELL $MAINFILE --porcelain -x $SWF_FILE
cd $SAVED_DIR
