function foo(x) {
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }
  if (x < 0) { return x; }

  return x;
}


trace(foo(100));