user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("browser.rights.3.shown", true);
user_pref("shumway.ignoreCTP", true);
user_pref("browser.displayedE10SPrompt", 5);
user_pref("browser.displayedE10SPrompt.1", 5);
user_pref("browser.displayedE10SNotice", 2);
user_pref("browser.tabs.remote.autostart", false);
user_pref("browser.tabs.remote.autostart.1", false);
