function Keyboard() {
}

Object.defineProperties(Keyboard, {
  capsLock: descAccessor(function () {
    return Stage.instance.$keyboard.capsLock;
  }),
  hasVirtualKeyboard: descAccessor(function () {
    return false; // TODO Stage.instance.$keyboard.hasVirtualKeyboard;
  }),
  numLock: descAccessor(function () {
    return Stage.instance.$keyboard.numLock;
  }),
  physicalKeyboardType: descAccessor(function () {
    return 'alphanumeric'; // TODO Stage.instance.$keyboard.physicalKeyboardType;
  }),
  isAccessible: descMethod(function () {
    return true; // TODO
  }),
  A:                    descConst(65),
  ALTERNATE:            descConst(18),
  AUDIO:                descConst(0x01000017),
  B:                    descConst(66),
  BACK:                 descConst(0x01000016),
  BACKQUOTE:            descConst(192),
  BACKSLASH:            descConst(220),
  BACKSPACE:            descConst(8),
  BLUE:                 descConst(0x01000003),
  C:                    descConst(67),
  CAPS_LOCK:            descConst(20),
  CHANNEL_DOWN:         descConst(0x01000005),
  CHANNEL_UP:           descConst(0x01000004),
  COMMA:                descConst(188),
  COMMAND:              descConst(15),
  CONTROL:              descConst(17),
  D:                    descConst(68),
  DELETE:               descConst(46),
  DOWN:                 descConst(40),
  DVR:                  descConst(0x01000019),
  E:                    descConst(69),
  END:                  descConst(35),
  ENTER:                descConst(13),
  EQUAL:                descConst(187),
  ESCAPE:               descConst(27),
  EXIT:                 descConst(0x01000015),
  F:                    descConst(70),
  F1:                   descConst(112),
  F10:                  descConst(121),
  F11:                  descConst(122),
  F12:                  descConst(123),
  F13:                  descConst(124),
  F14:                  descConst(125),
  F15:                  descConst(126),
  F2:                   descConst(113),
  F3:                   descConst(114),
  F4:                   descConst(115),
  F5:                   descConst(116),
  F6:                   descConst(117),
  F7:                   descConst(118),
  F8:                   descConst(119),
  F9:                   descConst(120),
  FAST_FORWARD:         descConst(0x0100000A),
  G:                    descConst(71),
  GREEN:                descConst(0x01000001),
  GUIDE:                descConst(0x01000014),
  H:                    descConst(72),
  HELP:                 descConst(0x0100001D),
  HOME:                 descConst(36),
  I:                    descConst(73),
  INFO:                 descConst(0x01000013),
  INPUT:                descConst(0x0100001B),
  INSERT:               descConst(45),
  J:                    descConst(74),
  K:                    descConst(75),
  KEYNAME_BEGIN:        descConst('Begin'),
  KEYNAME_BREAK:        descConst('Break'),
  KEYNAME_CLEARDISPLAY: descConst('ClrDsp'),
  KEYNAME_CLEARLINE:    descConst('ClrLn'),
  KEYNAME_DELETE:       descConst('Delete'),
  KEYNAME_DELETECHAR:   descConst('DelChr'),
  KEYNAME_DELETELINE:   descConst('DelLn'),
  KEYNAME_DOWNARROW:    descConst('Down'),
  KEYNAME_END:          descConst('End'),
  KEYNAME_EXECUTE:      descConst('Exec'),
  KEYNAME_F1:           descConst('F1'),
  KEYNAME_F10:          descConst('F10'),
  KEYNAME_F11:          descConst('F11'),
  KEYNAME_F12:          descConst('F12'),
  KEYNAME_F13:          descConst('F13'),
  KEYNAME_F14:          descConst('F14'),
  KEYNAME_F15:          descConst('F15'),
  KEYNAME_F16:          descConst('F16'),
  KEYNAME_F17:          descConst('F17'),
  KEYNAME_F18:          descConst('F18'),
  KEYNAME_F19:          descConst('F19'),
  KEYNAME_F2:           descConst('F2'),
  KEYNAME_F20:          descConst('F20'),
  KEYNAME_F21:          descConst('F21'),
  KEYNAME_F22:          descConst('F22'),
  KEYNAME_F23:          descConst('F23'),
  KEYNAME_F24:          descConst('F24'),
  KEYNAME_F25:          descConst('F25'),
  KEYNAME_F26:          descConst('F26'),
  KEYNAME_F27:          descConst('F27'),
  KEYNAME_F28:          descConst('F28'),
  KEYNAME_F29:          descConst('F29'),
  KEYNAME_F3:           descConst('F3'),
  KEYNAME_F30:          descConst('F30'),
  KEYNAME_F31:          descConst('F31'),
  KEYNAME_F32:          descConst('F32'),
  KEYNAME_F33:          descConst('F33'),
  KEYNAME_F34:          descConst('F34'),
  KEYNAME_F35:          descConst('F35'),
  KEYNAME_F4:           descConst('F4'),
  KEYNAME_F5:           descConst('F5'),
  KEYNAME_F6:           descConst('F6'),
  KEYNAME_F7:           descConst('F7'),
  KEYNAME_F8:           descConst('F8'),
  KEYNAME_F9:           descConst('F9'),
  KEYNAME_FIND:         descConst('Find'),
  KEYNAME_HELP:         descConst('Help'),
  KEYNAME_HOME:         descConst('Home'),
  KEYNAME_INSERT:       descConst('Insert'),
  KEYNAME_INSERTCHAR:   descConst('InsChr'),
  KEYNAME_INSERTLINE:   descConst('InsLn'),
  KEYNAME_LEFTARROW:    descConst('Left'),
  KEYNAME_MENU:         descConst('Menu'),
  KEYNAME_MODESWITCH:   descConst('ModeSw'),
  KEYNAME_NEXT:         descConst('Next'),
  KEYNAME_PAGEDOWN:     descConst('PgDn'),
  KEYNAME_PAGEUP:       descConst('PgUp'),
  KEYNAME_PAUSE:        descConst('Pause'),
  KEYNAME_PREV:         descConst('Prev'),
  KEYNAME_PRINT:        descConst('Print'),
  KEYNAME_PRINTSCREEN:  descConst('PrntScrn'),
  KEYNAME_REDO:         descConst('Redo'),
  KEYNAME_RESET:        descConst('Reset'),
  KEYNAME_RIGHTARROW:   descConst('Right'),
  KEYNAME_SCROLLLOCK:   descConst('ScrlLck'),
  KEYNAME_SELECT:       descConst('Select'),
  KEYNAME_STOP:         descConst('Stop'),
  KEYNAME_SYSREQ:       descConst('SysReq'),
  KEYNAME_SYSTEM:       descConst('Sys'),
  KEYNAME_UNDO:         descConst('Undo'),
  KEYNAME_UPARROW:      descConst('Up'),
  KEYNAME_USER:         descConst('User'),
  L:                    descConst(76),
  LAST:                 descConst(0x01000011),
  LEFT:                 descConst(37),
  LEFTBRACKET:          descConst(219),
  LIVE:                 descConst(0x01000010),
  M:                    descConst(77),
  MASTER_SHELL:         descConst(0x0100001E),
  MENU:                 descConst(0x01000012),
  MINUS:                descConst(189),
  N:                    descConst(78),
  NEXT:                 descConst(0x0100000E),
  NUMBER_0:             descConst(48),
  NUMBER_1:             descConst(49),
  NUMBER_2:             descConst(50),
  NUMBER_3:             descConst(51),
  NUMBER_4:             descConst(52),
  NUMBER_5:             descConst(53),
  NUMBER_6:             descConst(54),
  NUMBER_7:             descConst(55),
  NUMBER_8:             descConst(56),
  NUMBER_9:             descConst(57),
  NUMPAD:               descConst(21),
  NUMPAD_0:             descConst(96),
  NUMPAD_1:             descConst(97),
  NUMPAD_2:             descConst(98),
  NUMPAD_3:             descConst(99),
  NUMPAD_4:             descConst(100),
  NUMPAD_5:             descConst(101),
  NUMPAD_6:             descConst(102),
  NUMPAD_7:             descConst(103),
  NUMPAD_8:             descConst(104),
  NUMPAD_9:             descConst(105),
  NUMPAD_ADD:           descConst(107),
  NUMPAD_DECIMAL:       descConst(110),
  NUMPAD_DIVIDE:        descConst(111),
  NUMPAD_ENTER:         descConst(108),
  NUMPAD_MULTIPLY:      descConst(106),
  NUMPAD_SUBTRACT:      descConst(109),
  O:                    descConst(79),
  P:                    descConst(80),
  PAGE_DOWN:            descConst(34),
  PAGE_UP:              descConst(33),
  PAUSE:                descConst(0x01000008),
  PERIOD:               descConst(190),
  PLAY:                 descConst(0x01000007),
  PREVIOUS:             descConst(0x0100000F),
  Q:                    descConst(81),
  QUOTE:                descConst(222),
  R:                    descConst(82),
  RECORD:               descConst(0x01000006),
  RED:                  descConst(0x01000000),
  REWIND:               descConst(0x0100000B),
  RIGHT:                descConst(39),
  RIGHTBRACKET:         descConst(221),
  S:                    descConst(83),
  SEARCH:               descConst(0x0100001F),
  SEMICOLON:            descConst(186),
  SETUP:                descConst(0x0100001C),
  SHIFT:                descConst(16),
  SKIP_BACKWARD:        descConst(0x0100000D),
  SKIP_FORWARD:         descConst(0x0100000C),
  SLASH:                descConst(191),
  SPACE:                descConst(32),
  STOP:                 descConst(0x01000009),
  STRING_BEGIN:         descConst('\uF72A'),
  STRING_BREAK:         descConst('\uF732'),
  STRING_CLEARDISPLAY:  descConst('\uF73A'),
  STRING_CLEARLINE:     descConst('\uF739'),
  STRING_DELETE:        descConst('\uF728'),
  STRING_DELETECHAR:    descConst('\uF73E'),
  STRING_DELETELINE:    descConst('\uF73C'),
  STRING_DOWNARROW:     descConst('\uF701'),
  STRING_END:           descConst('\uF72B'),
  STRING_EXECUTE:       descConst('\uF742'),
  STRING_F1:            descConst('\uF704'),
  STRING_F10:           descConst('\uF70D'),
  STRING_F11:           descConst('\uF70E'),
  STRING_F12:           descConst('\uF70F'),
  STRING_F13:           descConst('\uF710'),
  STRING_F14:           descConst('\uF711'),
  STRING_F15:           descConst('\uF712'),
  STRING_F16:           descConst('\uF713'),
  STRING_F17:           descConst('\uF714'),
  STRING_F18:           descConst('\uF715'),
  STRING_F19:           descConst('\uF716'),
  STRING_F2:            descConst('\uF705'),
  STRING_F20:           descConst('\uF717'),
  STRING_F21:           descConst('\uF718'),
  STRING_F22:           descConst('\uF719'),
  STRING_F23:           descConst('\uF71A'),
  STRING_F24:           descConst('\uF71B'),
  STRING_F25:           descConst('\uF71C'),
  STRING_F26:           descConst('\uF71D'),
  STRING_F27:           descConst('\uF71E'),
  STRING_F28:           descConst('\uF71F'),
  STRING_F29:           descConst('\uF720'),
  STRING_F3:            descConst('\uF706'),
  STRING_F30:           descConst('\uF721'),
  STRING_F31:           descConst('\uF722'),
  STRING_F32:           descConst('\uF723'),
  STRING_F33:           descConst('\uF724'),
  STRING_F34:           descConst('\uF725'),
  STRING_F35:           descConst('\uF726'),
  STRING_F4:            descConst('\uF707'),
  STRING_F5:            descConst('\uF708'),
  STRING_F6:            descConst('\uF709'),
  STRING_F7:            descConst('\uF70A'),
  STRING_F8:            descConst('\uF70B'),
  STRING_F9:            descConst('\uF70C'),
  STRING_FIND:          descConst('\uF745'),
  STRING_HELP:          descConst('\uF746'),
  STRING_HOME:          descConst('\uF729'),
  STRING_INSERT:        descConst('\uF727'),
  STRING_INSERTCHAR:    descConst('\uF73D'),
  STRING_INSERTLINE:    descConst('\uF73B'),
  STRING_LEFTARROW:     descConst('\uF702'),
  STRING_MENU:          descConst('\uF735'),
  STRING_MODESWITCH:    descConst('\uF747'),
  STRING_NEXT:          descConst('\uF740'),
  STRING_PAGEDOWN:      descConst('\uF72D'),
  STRING_PAGEUP:        descConst('\uF72C'),
  STRING_PAUSE:         descConst('\uF730'),
  STRING_PREV:          descConst('\uF73F'),
  STRING_PRINT:         descConst('\uF738'),
  STRING_PRINTSCREEN:   descConst('\uF72E'),
  STRING_REDO:          descConst('\uF744'),
  STRING_RESET:         descConst('\uF733'),
  STRING_RIGHTARROW:    descConst('\uF703'),
  STRING_SCROLLLOCK:    descConst('\uF72F'),
  STRING_SELECT:        descConst('\uF741'),
  STRING_STOP:          descConst('\uF734'),
  STRING_SYSREQ:        descConst('\uF731'),
  STRING_SYSTEM:        descConst('\uF737'),
  STRING_UNDO:          descConst('\uF743'),
  STRING_UPARROW:       descConst('\uF700'),
  STRING_USER:          descConst('\uF736'),
  SUBTITLE:             descConst(0x01000018),
  T:                    descConst(84),
  TAB:                  descConst(9),
  U:                    descConst(85),
  UP:                   descConst(38),
  V:                    descConst(86),
  VOD:                  descConst(0x0100001A),
  W:                    descConst(87),
  X:                    descConst(88),
  Y:                    descConst(89),
  YELLOW:               descConst(0x01000002),
  Z:                    descConst(90),
});

Object.defineProperties(Keyboard, {
  CharCodeStrings:      descConst([
    Keyboard.KEYNAME_BEGIN,
    Keyboard.KEYNAME_BREAK,
    Keyboard.KEYNAME_CLEARDISPLAY,
    Keyboard.KEYNAME_CLEARLINE,
    Keyboard.KEYNAME_DELETE,
    Keyboard.KEYNAME_DELETECHAR,
    Keyboard.KEYNAME_DELETELINE,
    Keyboard.KEYNAME_DOWNARROW,
    Keyboard.KEYNAME_END,
    Keyboard.KEYNAME_EXECUTE,
    Keyboard.KEYNAME_F1,
    Keyboard.KEYNAME_F10,
    Keyboard.KEYNAME_F11,
    Keyboard.KEYNAME_F12,
    Keyboard.KEYNAME_F13,
    Keyboard.KEYNAME_F14,
    Keyboard.KEYNAME_F15,
    Keyboard.KEYNAME_F16,
    Keyboard.KEYNAME_F17,
    Keyboard.KEYNAME_F18,
    Keyboard.KEYNAME_F19,
    Keyboard.KEYNAME_F2,
    Keyboard.KEYNAME_F20,
    Keyboard.KEYNAME_F21,
    Keyboard.KEYNAME_F22,
    Keyboard.KEYNAME_F23,
    Keyboard.KEYNAME_F24,
    Keyboard.KEYNAME_F25,
    Keyboard.KEYNAME_F26,
    Keyboard.KEYNAME_F27,
    Keyboard.KEYNAME_F28,
    Keyboard.KEYNAME_F29,
    Keyboard.KEYNAME_F3,
    Keyboard.KEYNAME_F30,
    Keyboard.KEYNAME_F31,
    Keyboard.KEYNAME_F32,
    Keyboard.KEYNAME_F33,
    Keyboard.KEYNAME_F34,
    Keyboard.KEYNAME_F35,
    Keyboard.KEYNAME_F4,
    Keyboard.KEYNAME_F5,
    Keyboard.KEYNAME_F6,
    Keyboard.KEYNAME_F7,
    Keyboard.KEYNAME_F8,
    Keyboard.KEYNAME_F9,
    Keyboard.KEYNAME_FIND,
    Keyboard.KEYNAME_HELP,
    Keyboard.KEYNAME_HOME,
    Keyboard.KEYNAME_INSERT,
    Keyboard.KEYNAME_INSERTCHAR,
    Keyboard.KEYNAME_INSERTLINE,
    Keyboard.KEYNAME_LEFTARROW,
    Keyboard.KEYNAME_MENU,
    Keyboard.KEYNAME_MODESWITCH,
    Keyboard.KEYNAME_NEXT,
    Keyboard.KEYNAME_PAGEDOWN,
    Keyboard.KEYNAME_PAGEUP,
    Keyboard.KEYNAME_PAUSE,
    Keyboard.KEYNAME_PREV,
    Keyboard.KEYNAME_PRINT,
    Keyboard.KEYNAME_PRINTSCREEN,
    Keyboard.KEYNAME_REDO,
    Keyboard.KEYNAME_RESET,
    Keyboard.KEYNAME_RIGHTARROW,
    Keyboard.KEYNAME_SCROLLLOCK,
    Keyboard.KEYNAME_SELECT,
    Keyboard.KEYNAME_STOP,
    Keyboard.KEYNAME_SYSREQ,
    Keyboard.KEYNAME_SYSTEM,
    Keyboard.KEYNAME_UNDO,
    Keyboard.KEYNAME_UPARROW,
    Keyboard.KEYNAME_USER
  ])
});
